language: java
jdk:
  - oraclejdk7

install: true
script:
  - "cd modules;mvn clean test"
  - jdk_switcher use oraclejdk8 
  - "mvn clean test"
  - mvn clean package -Dmaven.test.skip=true
  - jdk_switcher use oraclejdk7
  - "mvn test"
  - "mvn clean package -Dmaven.test.skip=true" 
  - jdk_switcher use oraclejdk7
  - "mvn test"  

branches:
  only:
    - master 
