#!/bin/bash

echo "[Pre-Requirement] Makesure install JDK 6.0+ and set the JAVA_HOME."
echo "[Pre-Requirement] Makesure install Maven 3.0.3+ and set the PATH."
	
set MAVEN_OPTS=$MAVEN_OPTS -XX:MaxPermSize=128m

echo "[Step 1] Install all springside modules and archetype to local maven repository."
cd modules
mvn clean install -Dmaven.test.skip=true

cd ../support/maven-archetype
mvn clean install
cd ../../

echo "[Step 2] Initialize schema and data for all example projects."
cd examples
mvn antrun:run -Prefresh-db
cd ..

echo "[Step 3] Start all example projects."
cd  examples/quickstart
mvn clean jetty:run &
cd  ../showcase
mvn clean jetty:run -Djetty.port=8081 &

echo "[INFO] Please wait a moment then access below demo sites:"
echo "[INFO] http://localhost:8080/quickstart"
echo "[INFO] http://localhost:8081/showcase"

