#!/bin/bash

echo "[Pre-Requirement] Makesure install JDK 6.0+ and set the JAVA_HOME."
echo "[Pre-Requirement] Makesure install Maven 3.0.4+ and set the PATH."
	
set MAVEN_OPTS=$MAVEN_OPTS -XX:MaxPermSize=128m

echo "[Step 1] Install all springside modules to local maven repository, and generate eclipse files to all projects."
mvn clean install -Pmodules -Dmaven.test.skip=true

echo "[Step 2] Generate Eclipse project files for all projects"	
mvn eclipse:clean eclipse:eclipse -Pall 
 
echo "[Step 3] Start H2 Standalone database."
cd support/h2
mvn exec:java -PwithoutBrowser &
cd ../../

echo "[Step 4] Init schema and data for all example projects."
mvn antrun:run -Prefresh-db,examples

echo "[Step 5] Start all example projects."
cd  examples/mini-service
mvn clean jetty:run -Djetty.port=8082 &
cd  ../mini-web
mvn clean jetty:run -Djetty.port=8081 &
cd  ../showcase
mvn clean jetty:run &

echo "[INFO] Please wait a moment then access below demo sites:"
echo "[INFO] http://localhost:8082/mini-service"
echo "[INFO] http://localhost:8081/mini-web"
echo "[INFO] http://localhost:8080/showcase"

