create table ss_task (
	id bigint generated by default as identity,
	title varchar(128) not null,
	description varchar(255),
	user_id bigint not null,
    primary key (id)
);

create table ss_user (
	id bigint generated by default as identity,
	name varchar(64) not null,
	primary key (id)
);