    drop table if exists acct_department;

    drop table if exists acct_user;

    create table acct_department (
        id bigint generated by default as identity,
        manager_id bigint,
        name varchar(255) not null unique,
        primary key (id)
    ) ;

    create table acct_user (
        id bigint generated by default as identity,
        department_id bigint,
        login_name varchar(255) not null unique,
        name varchar(255),
        password varchar(255),
        email varchar(255),
        primary key (id)
    ) ;